### PR TITLE
Fix CausalRandomForestRegressor.fit() on scikit-learn 1.9

### LINKED ISSUE #905: CausalRandomForestRegressor.fit() fails on scikit-learn 1.9 (forest sampler signature change)
**Describe the bug**

After #903 fixed the import error (#902), `CausalRandomForestRegressor.fit()` still fails on scikit-learn 1.9.

`causalml/inference/tree/causal/causalforest.py` vendors scikit-learn's `BaseForest._fit()` internals (to thread the `treatment` vector through `_parallel_build_trees`), so it calls several private forest helpers directly. scikit-learn 1.9 ([scikit-learn#31529](https://github.com/scikit-learn/scikit-learn/pull/31529)) made `sample_weight` a required argument on these helpers:

- `BaseForest._validate_y_class_weight(y)` → `(y, sample_weight)`
- `_generate_sample_indices(random_state, n_samples, n_samples_bootstrap)` → `(..., sample_weight)`
- `_get_n_samples_bootstrap(n_samples, max_samples)` → `(..., sample_weight)`

**To Reproduce**

```
pip install -U causalml
pip install 'scikit-learn==1.9.0'
```
```python
from causalml.dataset import synthetic_data
from causalml.inference.tree import CausalRandomForestRegressor

y, X, w, *_ = synthetic_data(mode=1, n=500, p=5, sigma=1.0)
CausalRandomForestRegressor(control_name=0).fit(X=X, treatment=w, y=y)
```
```
TypeError: BaseForest._validate_y_class_weight() missing 1 required positional argument: 'sample_weight'
  .../causalml/inference/tree/causal/causalforest.py  (in _fit)
```

**Expected behavior**

`fit()` / `predict()` work on scikit-learn 1.9 with results unchanged from earlier versions.

**Fix**

Version-guard the three calls, passing `sample_weight=None` on >= 1.9. On 1.9, `_generate_sample_indices(..., None)` runs the identical uniform `randint` draw and `_get_n_samples_bootstrap(..., None)` keeps the old unweighted semantics, so causal-forest predictions are **bit-for-bit identical** across versions (the vendored `_parallel_build_trees` already applies the user's `sample_weight`). PR incoming.

**Note:** `calculate_error()` has a separate, independent incompatibility via `forestci` — tracked in #906.

### PR DESCRIPTION
**Pull request by jeongyoonlee**
## Summary

`fit()` on `CausalRandomForestRegressor` raised `TypeError` under scikit-learn 1.9, even after #903 fixed the import error (#902, by @jakevdp). `causalforest.py` vendors scikit-learn's `BaseForest._fit()` internals (to thread the `treatment` vector through `_parallel_build_trees`), so it calls private forest helpers directly. scikit-learn 1.9 ([scikit-learn#31529](https://github.com/scikit-learn/scikit-learn/pull/31529)) made `sample_weight` a **required** argument on three of them.

Fixes #905.

## Changes

A module-level `_SKLEARN_GE_19` flag gates three version-guarded calls:

| helper | pre-1.9 | 1.9 |
|---|---|---|
| `_generate_sample_indices` | `(rs, n, n_boot)` | `(rs, n, n_boot, None)` |
| `_validate_y_class_weight` | `(y)` | `(y, sample_weight)` |
| `_get_n_samples_bootstrap` | `(n, max_samples)` | `(n, max_samples, sample_weight=None)` |

The flag compares against `"1.9.0.dev0"` (not `"1.9.0"`) so 1.9 **pre-releases** — e.g. `1.9.0rc1`, which already carries the new signatures and sorts *before* `1.9.0` under PEP 440 — also take the `>=1.9` path.

## Behavior preserved (bit-for-bit)

Passing `sample_weight=None` on 1.9 is deliberate: `_generate_sample_indices(..., None)` runs the identical uniform `randint` draw, and `_get_n_samples_bootstrap(..., None)` keeps the old unweighted semantics. The vendored `_parallel_build_trees` already applies the user's `sample_weight` itself, so this is a pure compatibility fix, not a behavior change. Verified: with a fixed seed, CRF predictions on 1.7.0 vs 1.9.0 are **identical** (max abs diff `0.0`).

## Testing

`tests/test_causal_trees.py`, run against a real install of each version:

- **scikit-learn 1.7.0:** 20 passed
- **scikit-learn 1.9.0:** 18 passed, 2 xfailed

## Known limitation — `calculate_error()` (deferred to #906)

`calculate_error()` delegates to the third-party `forestci` package, which has its **own** independent sklearn-1.9 incompatibility (it calls the same private samplers with the pre-1.9 arity and has no version guard; latest `forestci` 0.7/master is still unfixed). Its `calibrate=True` path recomputes `inbag` internally, so passing a precomputed `inbag` doesn't avoid it. This is out of scope here and tracked in #906; the two affected test cases are marked **non-strict** `xfail` on sklearn `>=1.9` (so they auto-XPASS once forestci is fixed), and the `calculate_error()` docstring documents the limitation. `fit()` / `predict()` are unaffected.

Builds on #903 by @jakevdp.

### CODE REVIEW

**Review by ras44 — APPROVED** [review]
LGTM
